pipeline {
  agent none

  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        script {
          if (env.CHANGE_ID) {
            echo "Build triggered by Pull Request #${env.CHANGE_ID}"
          } else {
            echo "Build triggered by push/merge on branch ${env.BRANCH_NAME}"
          }
        }
        sh 'mvn --version'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        script {
          if (env.CHANGE_ID) {
            echo "Front-end build: Pull Request #${env.CHANGE_ID}"
          } else {
            echo "Front-end build: push/merge on branch ${env.BRANCH_NAME}"
          }
        }
        sh 'node --version'
      }
    }
  }
}
